import React from 'react'
import Header from '../../Components/Header/Header'
import Footer from '../../Components/Footer/Footer'

const PrivacyPolicy = () => {
    return (
        <div>
            <Header />
            <div className='p-[40px_0] max-w-[1300px] mx-auto px-[20px]'>
                <h2 className='text-[#3e337c] sm:text-[28px] text-[20px] text-center font-semibold'>PRIVACY POLICY</h2>
                <p className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[30px]'>Thank you for visiting website <span className='font-bold'>(“Website”)</span> / mobile application <span className='font-bold'>(“App”)</span> of MDNTechnologies Private Limited <span className='font-bold'>(“Atomberg”)</span>. Users, customers, visitors and vendors are collectively referred to as <span className='font-bold'>“you”</span> or <span className='font-bold'>“your”</span>.</p>
                <p className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px]'>By accessing or using the Website / App, or by otherwise giving us your information, you confirm that you have the capacity to enter into a legally binding contract under the Indian Contract Act, 1872, and have read, understood, and agree with the privacy practices described in this document, read with the Terms <span className='font-bold'>("Privacy Policy”)</span> and the collection, storage, processing, use, sharing, disclosure, or transfer of your personal information in accordance with the Privacy Policy. Please go through this Privacy Policy in detail and contact us if you have any questions or require any clarifications. If you do not agree with any of the terms and conditions of this Privacy Policy, please do not proceed further to use this Website / App.</p>
                <p className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px]'>This policy describes the manner in which Atomberg, owner and operator of the Website / App collects, uses, discloses, or otherwise processes your information when you visit the Website / App. We reserve the right to change, modify, add or delete portions of this Privacy Policy, at our sole discretion, at any time. While the Company will periodically inform you of this Privacy Policy or any material changes to this Privacy Policy that the Company makes, via email, you are responsible to check this page regularly to make note of any changes. Your continued use of the Website / App means that you accept and agree to the changes in the Privacy Policy.</p>
                <p className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px]'>If you are accessing or using our Website / App from an overseas location, you do so at your own risk, and shall be solely liable for compliance with any applicable local laws.</p>
                <p className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px]'>This Privacy Policy is published in compliance with, inter alia:</p>
                <ol className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px] flex gap-[10px] flex-col'>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(a)</span>Section 43A of the Information Technology Act, 2000 (“IT Act”) ;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(b)</span>Rule 4 of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011 ("SPDI Rules"); and</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(c)</span>Regulation 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 (“Intermediary Guidelines”).</li>
                </ol>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>What data is collected?</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We strive to only collect Personal Information that is adequate, relevant, and limited to achieve the purpose(s) for which it was collected. If you are a user visiting our Website / App, you understand that certain personal information in the nature of name, email address, phone number, residential address, designation, location, etc. may be collected from you.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>The Website / App may use cookie and tracking technology (recording information such as internet domain and host names, internet protocol (IP) addresses, browser software and operating system types, stream patterns, and dates and times that the Website / App is accessed) depending on the features offered. Cookie and tracking technology are useful for gathering information such as browser type and operating system, tracking the number of visitors to the Website / App, and understanding how visitors use the Website / App. Cookies can also help customize the Website / App.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We may also collect personal information that you provide to us on our Website / App., register with us, post feedback, participate in any online survey, interact with us on social media, fill out any contact forms for us to assist you on the request raised by you, provide it to us directly such as through business interactions with you or when you visit one of our locations. For example, if you visit our office premises, we may ask that you provide us your first and last name, business association, and email address in order to identify you as a visitor.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>At all times, you may refuse all cookies on your browser by changing your settings to the extent permissible on your device. Further, all emails and newsletters from this Website / App allow you to opt out of further mailings. However, by doing so, you may not be able to use certain features on the Website / App or take full advantage of all the offerings and interest-based advertising.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>For further information, refer to this sheet:</p>
                <a href='#/' className='sm:text-[14px] text-[12px] text-[#3e337c] underline break-all' >https://docs.google.com/spreadsheets/d/19T2N7cIKx98Y643lGfewJXQk5i6P6l2BeoNfctEz9sY/edit?usp=sharing</a>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>Who has access to this data?</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>The data stored on the cloud will be primarily accessed by Atomberg’s engineering and data teams. You should be aware that some of the Personal Information that may have been shared on third-party websites may still continue to be available as we do not have control over these websites. Your Personal Information may also appear in online searches.. You should only share Personal Information with people that you trust because they will be able to save it or re-share it with others, including when they sync the Personal Information to a device.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>Purpose of data collected?</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We use the Personal Information including SPDI we collect to make the Website / App more effective. We may also use your Personal Information and SPDI for the following purposes:</p>
                <ol className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px] flex gap-[10px] flex-col'>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(a)</span>our Website / App.to analyze user activity on the Website / App and understand user preferences in order to improve the functionalities on the Website/App;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(b)</span>for research, analytical and statistical purposes, including for the purpose of providing goods and services;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(c)</span>for non-targeting reasons such as frequency capping, compliance, information reporting or delivery, market research or product development purposes;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(d)</span>to conduct audits and quality assessment procedures;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(e)</span>to screen for potential risk and fraud, and more generally to improve and optimize our Website / App (for example, by generating analytics about how our users browse and interact with the Website / App, and to assess the success of our marketing and advertising campaigns);</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(f)</span>to investigate, prevent, or take action regarding illegal activities or situations involving potential threats to the safety of any person including that of our employees, safety of the Company’s assets, violations of our Terms, or as otherwise required by law;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(g)</span>to identify the sender and handle your requests and to otherwise communicate with you;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(h)</span>when in line with the preferences you have shared with us, provide you with information or advertising relating to our newsletters and other marketing content;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(i)</span>for direct marketing content to users through various channels, including via e-mail, MMS/SMS or by phone. Such actions are taken by the Company only if you have given your consent, which may be withdrawn at any time;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(j)</span>in some cases, to carry out direct marketing via traditional mail. You will be informed separately about the intention to conduct this type of marketing;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(k)</span>to support our relationship with you and the business with which you are associated, including customer or technical support services, and accounting and billing services;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(l)</span>to request feedback;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(m)</span>to establish and pursue claims or defend against claims;</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(n)</span>to comply with applicable law; or</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(o)</span>for any other purposes that are permissible under applicable law,</li>
                </ol>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] my-[20px]'>(collectively <span className='font-bold'>“Purposes”</span>).</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We may combine the information that we receive from third parties with the information you give to us and information we collect about you for the Purposes set out above. Further, we may anonymize and/or de-identify information collected via other means, including via the use of third-party web analytic tools and such anonymized / de-identified information’s use is not restricted by this Privacy Policy, and it may be used and disclosed to others without limitation.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>It is clarified that the data on your local phone will be deleted as soon as you uninstall the App. The data on the cloud will remain indefinitely, unless you ask for the data to be deleted or in case of Personal Information, unless the Purpose of such collected Personal Information expires.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>How do we share your Personal Information?</h3>
                <ol className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px] flex gap-[10px] flex-col'>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-[40px]'>(a)</span>Information shared with partners, service providers or group companies: Information about you and the other users of the Website / App form an integral part of our business. By using the Website / App, you accept the terms hereof and hereby consent to the storage and processing of the Personal Information by third parties. We have arrangements with third parties service providers including financial service providers, etc., who are the intended recipients and may have access to the Personal Information but shall not disclose such information further to any other individual / entity. When we share information with third parties, we do so after ensuring that such third party has implemented data protection measures at least as protective as those described in this Privacy Policy or as required under applicable law and after ensuring that such third party shall not disclose your Personal Information further to any other individual / entity. By using the Website / App, you accept the terms hereof and hereby consent to the storage and processing of the Personal Information and SPDI by third parties.</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-[40px]'>(a)</span>Our Legal obligations: We may release your Personal Information when we believe in good faith that such release is appropriate to comply with applicable law including to: (i) conform to legal requirements or comply with legal processes; (ii) protect rights or property of affiliated companies; (iii) prevent a crime or in interest of national security; or (iv) protect personal safety of our users or the public. We may also disclose your Personal Information to enforce or apply our Terms and other agreements; or protect the rights, property or our safety, safety of our users or others. This includes exchanging information with other companies, organisations, government or regulatory authorities for fraud protection and credit risk reduction.</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-[40px]'>(a)</span>Sharing upon merger or amalgamation or intra-group transfer: Any third party to which we transfer or sell our assets, merge or consolidate with, will have the right to continue to use the Personal Information provided to us by you, in accordance with the Terms and this Privacy Policy. We may disclose information to our partners, affiliates, subsidiaries, group entities, investors, stakeholders or potential associates in an anonymized and aggregate manner, so that they too may understand how users use our Website / App. or engage with us on the Website / App and enable us to create a better overall experience for you.</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-[40px]'>(a)</span>Transfer to affiliates of the Company, third parties and outside India: Subject to applicable law, we may at our sole discretion, transfer Personal Information to any other body corporate (as defined under the Information Technology Act, 2000) or a person that ensures at least the same level of data protection as is provided by us under the terms hereof, located in India or any other country. By using the Website / App, you accept the terms hereof and hereby consent to us sharing with and/or processing of your Personal Information and SPDI by our group companies, affiliates, service providers, consultants, or third parties, including in any location outside India, provided that they ensure that your SPDI is protected in compliance with standards that are comparable to the standards of protection afforded to it in India.</li>
                </ol>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>You may choose to not provide us with any or all information, but in the event that you do so, we may be unable to provide you with our services or modify the nature of our relationship with you.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>How do we share your Personal Information?</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We ensure that only authorized employees, agents and contractors (who have agreed to keep information secure and confidential) have access to this information. We use commercially reasonable physical, administrative, and technical safeguards to preserve the integrity and security of your Personal Data. Further, various security strategies are provided to effectively ensure data security of user and device.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>In order to protect your Personal Information in line with the applicable data privacy laws and regulations, we have implemented appropriate technical and organizational measures. Please be aware that the transmission of information via the internet is not completely secure. Although we will do our best to protect your Personal Information, we cannot guarantee the security of your data transmitted through the Website / App. Once we have received your information, we will use strict physical, electronic, and procedural safeguards to try to prevent unauthorised access.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>You agree that the security measures adopted by us are reasonable to protect your Personal Information. We disclaim any liability as a result of any breach of security or unintended loss or disclosure of your Personal Information.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>How can I ask for my data to be deleted?</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>At any time, you may give or withdraw your consent to us for collecting and processing your Personal Information, including in the manner and for the Purposes. You may withdraw or limit your consent at any time by going on ‘Settings’ on the Website / App, and click on ‘Delete Account’ option. This will delete all your personal data and anonymize your device-related data.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We may, however, reserve the right to retain and store your Personal Information for our business purposes, whether such Personal Information has been deleted or not, to the extent permitted by law.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Please note that your withdrawal of consent may result in us not being able to provide you with the services or terminate any existing relationship that we may have with you.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>How can I ask for all data related to myself and my devices?</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>You may review, the information that you have provided to us, at any point by writing to us at app@atomberg.com using the email ID registered with the App. On verifying the email address, we will send you the current snapshot of the data related to you and your products that’s available with us.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>Children’s privacy</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Use of the Website / App is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are under 18 years of age, then please do not use or access the Website / App at any time or in any manner. If you are a parent or guardian and discover that your child under 18 years of age has visited the Website / App, then you may alert us at app@atomberg.com and request that we delete that child’s Personal Information from our systems.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We do not knowingly collect any personal information from users who are less than 18 years of age. Upon discovery of any personal information of any child, we shall purge such personal information in accordance with applicable law.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>Social Media</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We maintain channels, pages, and accounts on some social media platforms in order to communicate with, support, and interact with staff members, partners, and clients/customers. To improve it’s products and services, we keep track of and log comments and postings made on various channels about the company.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Please be aware that you may not provide the following information to us via such social media sites:</p>
                <ol className='text-[#3e337c] sm:text-[14px] text-[12px] mt-[10px] flex gap-[10px] flex-col'>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(a)</span>Confidential information, such as any details relating to your finances, bank account information, transactions, etc.</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(b)</span>sensitive personal information, such as special categories of personal data include any information revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership,</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(c)</span>other sensitive personal data like criminal convictions and offences and national security information, and</li>
                    <li><span className='text-[#3e337c] sm:text-[14px] text-[12px] mr-3'>(d)</span>genetic data, biometric data processed for the purpose of uniquely identifying a natural person.</li>
                </ol>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Other than the content uploaded by our employees on our behalf, we are not liable for any information posted on those sites. we are only accountable for how it uses the personal information it receives from these sites.</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>Grievance redressal and contact us</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>If you have any queries about our practices or this Privacy Policy, please contact us as follows:</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Name of Grievance Officer - Kiran Bedi,
                    MDNTechnologies Private Limited</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Postal Mailing Address:
                    <span className='italic'> Office No. 1205, 12th Floor, Rupa Solitaire, Millennium Business Park,Thane-Belapur Road, Mahape Navi Mumbai 400710</span></p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Contact no:-
                    844 844 9442</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Email:
                    support@atomberg.com</p>
                <h3 className='text-[16px] font-semibold text-[#3e337c] mt-[30px]'>Miscellaneous</h3>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>You agree and undertake to indemnify us in any suit or dispute by any third party arising out of disclosure of information by you to third parties either through our Website/App or otherwise and your use and access of websites, applications and resources of third parties.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>Each clause of this Privacy Policy shall be and remain separate from and independent of and severable from all and any other clauses herein, except where otherwise expressly indicated or indicated by the context of the Privacy Policy. The decision or declaration that one or more clauses are null and void shall have no effect on remaining clauses of this Privacy Policy.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>MDNshall not be liable for any consequential, incidental, special, indirect, exemplary or punitive damages, or damages for any loss of profits, revenue or business, regardless of the nature of the claim.</p>
                <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>This Privacy Policy shall be governed by the laws of India as applicable between residents of India without regard to any principles of conflict of laws. Any and all disputes arising hereunder shall be subject to the exclusive jurisdiction of the courts at Mumbai, India.</p>
            </div>
            <div className='bg-[#f8f6ff] py-[40px] mb-[50px]'>
                <div className='max-w-[1300px] mx-auto px-[20px]'>
                    <h2 className='text-[#3e337c] sm:text-[28px] text-[20px] font-semibold'>PRIVACY CONTACT INFORMATION</h2>
                    <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>If you have any questions, concerns, or comments about our privacy policy you may contact us using the information below:</p>
                    <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>By E-mail: <span className='font-bold'>support@atomberg.com</span></p>
                    <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>By Phone: Contact Number: <span className='font-bold'>8448449442</span></p>
                    <p className='sm:text-[14px] text-[12px] text-[#3e337c] mt-[10px]'>We reserve the right to make changes to this policy. Any changes to this policy will be posted.</p>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default PrivacyPolicy